# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sender', models.CharField(max_length=20)),
                ('Recipient', models.CharField(max_length=20)),
                ('Message', models.CharField(max_length=20)),
            ],
        ),
    ]
