# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 13:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='Message',
            new_name='Mails',
        ),
    ]
