# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20160713_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='Mails',
            field=models.TextField(max_length=1000),
        ),
    ]
