# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-17 12:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20160714_0341'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
